### ISSUE TITLE
CT Script error for TWIXT

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gene-expression-essentials#125]
```
gene-expression-essentials : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Script error for: TWIXT/Animation
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: TWIXT/Animation
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1553633202853/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1553633202853/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/26/2019, 2:46:42 PM
gene-expression-essentials : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Script error for: TWIXT/Easing
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: TWIXT/Easing
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1553633202853/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1553633202853/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/26/2019, 2:46:42 PM
gene-expression-essentials : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Script error for: TWIXT/Animation
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: TWIXT/Animation
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1553633202853/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1553633202853/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/26/2019, 2:46:42 PM
gene-expression-essentials : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Script error for: TWIXT/Easing
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: TWIXT/Easing
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1553633202853/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1553633202853/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/26/2019, 2:46:42 PM
```

**Comment by jbphet** [comment]
Fixed by @samreid in 07b155d9a0922d26794ec9aec8d161c53ab89fbb, closing.
