### ISSUE TITLE
CT: should not be called if disposed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gene-expression-essentials#127]
Related to the assertion that was added to TinyEmitter in https://github.com/phetsims/axon/issues/242.

```
gene-expression-essentials : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559716411260:50:17)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559716411260:247:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559716411260:160:14)
    at TranscriptionFactor.ShapeChangingModelElement.disposeShapeChangingModelElement (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559716411260:60:26)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559716411260:76:12)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/MobileBiomolecule.js?bust=1559716411260:112:51)
    at MessengerRnaProductionModel.removeMobileBiomolecule (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559716411260:289:25)
    at MessengerRnaProductionModel.setTranscriptionFactorCount (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559716411260:384:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559716411260:80:12
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

gene-expression-essentials : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559739541314:50:17)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559739541314:247:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559739541314:160:14)
    at TranscriptionFactor.ShapeChangingModelElement.disposeShapeChangingModelElement (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559739541314:60:26)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559739541314:76:12)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/MobileBiomolecule.js?bust=1559739541314:112:51)
    at MessengerRnaProductionModel.removeMobileBiomolecule (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559739541314:289:25)
    at MessengerRnaProductionModel.setTranscriptionFactorCount (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559739541314:384:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559739541314:80:12
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

gene-expression-essentials : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559722138984:50:17)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559722138984:247:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559722138984:160:14)
    at TranscriptionFactor.ShapeChangingModelElement.disposeShapeChangingModelElement (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559722138984:60:26)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559722138984:76:12)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/MobileBiomolecule.js?bust=1559722138984:112:51)
    at MessengerRnaProductionModel.removeMobileBiomolecule (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559722138984:289:25)
    at MessengerRnaProductionModel.setTranscriptionFactorCount (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559722138984:384:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559722138984:89:12
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

gene-expression-essentials : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559731723308:50:17)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559731723308:247:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559731723308:160:14)
    at TranscriptionFactor.ShapeChangingModelElement.disposeShapeChangingModelElement (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559731723308:60:26)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559731723308:76:12)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/MobileBiomolecule.js?bust=1559731723308:112:51)
    at MessengerRnaProductionModel.removeMobileBiomolecule (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559731723308:289:25)
    at MessengerRnaProductionModel.setTranscriptionFactorCount (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559731723308:384:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559731723308:80:12
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

gene-expression-essentials : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559717219622:50:17)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559717219622:247:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559717219622:160:14)
    at TranscriptionFactor.ShapeChangingModelElement.disposeShapeChangingModelElement (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559717219622:60:26)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559717219622:76:12)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/MobileBiomolecule.js?bust=1559717219622:112:51)
    at MessengerRnaProductionModel.removeMobileBiomolecule (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559717219622:289:25)
    at MessengerRnaProductionModel.setTranscriptionFactorCount (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559717219622:384:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559717219622:80:12
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

gene-expression-essentials : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559734602808:50:17)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559734602808:247:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559734602808:160:14)
    at TranscriptionFactor.ShapeChangingModelElement.disposeShapeChangingModelElement (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559734602808:60:26)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/ShapeChangingModelElement.js?bust=1559734602808:76:12)
    at TranscriptionFactor.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/common/model/MobileBiomolecule.js?bust=1559734602808:112:51)
    at MessengerRnaProductionModel.removeMobileBiomolecule (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559734602808:289:25)
    at MessengerRnaProductionModel.setTranscriptionFactorCount (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559734602808:384:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/gene-expression-essentials/js/mrna-production/model/MessengerRnaProductionModel.js?bust=1559734602808:89:12
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM
```

**Comment by jbphet** [comment]
There was a property value that was being set after the property had been disposed.  I reverse the order, and it appears to have fixed the problem.  I'll watch for a couple rounds of CT, and if it looks good, I'll close.

**Comment by jbphet** [comment]
A round of continuous testing has been run since this commit, and the sim passed.  Closing.
