### ISSUE TITLE
CT scientific notation is not supported

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gene-expression-essentials#139]
```
gene-expression-essentials : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/gene-expression-essentials_en.html?continuousTest=%7B%22test%22%3A%5B%22gene-expression-essentials%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629276877034%22%2C%22timestamp%22%3A1629278803770%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: scientific notation is not supported: 1.9e-8
Error: Assertion failed: scientific notation is not supported: 1.9e-8
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/dot/js/Utils.js:835:17)
at HSlider.updateSiblingStepAttribute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:920:46)
at enabledRangeObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:328:16)
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/axon/js/Property.js:378:5)
at HSlider.initializeAccessibleValueHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:330:29)
at HSlider.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleSlider.js:77:14)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/Slider.js:326:10)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/HSlider.js:27:5)
at new ControllerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/js/common/view/ControllerNode.js:77:20)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:54:37 AM

----------------------------------

gene-expression-essentials : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/gene-expression-essentials_en.html?continuousTest=%7B%22test%22%3A%5B%22gene-expression-essentials%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629276877034%22%2C%22timestamp%22%3A1629294912765%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: scientific notation is not supported: 1.9e-8
Error: Assertion failed: scientific notation is not supported: 1.9e-8
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/dot/js/Utils.js:835:17)
at HSlider.updateSiblingStepAttribute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:920:46)
at enabledRangeObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:328:16)
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/axon/js/Property.js:378:5)
at HSlider.initializeAccessibleValueHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:330:29)
at HSlider.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleSlider.js:77:14)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/Slider.js:326:10)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/HSlider.js:27:5)
at new ControllerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/js/common/view/ControllerNode.js:77:20)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:54:37 AM

----------------------------------

gene-expression-essentials : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/gene-expression-essentials_en.html?continuousTest=%7B%22test%22%3A%5B%22gene-expression-essentials%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1629276877034%22%2C%22timestamp%22%3A1629293403387%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: scientific notation is not supported: 1.9e-8
Error: Assertion failed: scientific notation is not supported: 1.9e-8
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/dot/js/Utils.js:835:17)
at HSlider.updateSiblingStepAttribute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:920:46)
at enabledRangeObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:328:16)
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/axon/js/Property.js:378:5)
at HSlider.initializeAccessibleValueHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:330:29)
at HSlider.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleSlider.js:77:14)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/Slider.js:326:10)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/HSlider.js:27:5)
at new ControllerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/js/common/view/ControllerNode.js:77:20)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:54:37 AM

----------------------------------

gene-expression-essentials : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/gene-expression-essentials_en.html?continuousTest=%7B%22test%22%3A%5B%22gene-expression-essentials%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629276877034%22%2C%22timestamp%22%3A1629280974910%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: scientific notation is not supported: 1.9e-8
Error: Assertion failed: scientific notation is not supported: 1.9e-8
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/dot/js/Utils.js:835:17)
at HSlider.updateSiblingStepAttribute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:920:46)
at enabledRangeObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:328:16)
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/axon/js/Property.js:378:5)
at HSlider.initializeAccessibleValueHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:330:29)
at HSlider.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleSlider.js:77:14)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/Slider.js:326:10)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/HSlider.js:27:5)
at new ControllerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/js/common/view/ControllerNode.js:77:20)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:54:37 AM

----------------------------------

gene-expression-essentials : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/gene-expression-essentials_en.html?continuousTest=%7B%22test%22%3A%5B%22gene-expression-essentials%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629276877034%22%2C%22timestamp%22%3A1629294917765%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: scientific notation is not supported: 1.9e-8
Error: Assertion failed: scientific notation is not supported: 1.9e-8
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/dot/js/Utils.js:835:17)
at HSlider.updateSiblingStepAttribute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:920:46)
at enabledRangeObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:328:16)
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/axon/js/Property.js:378:5)
at HSlider.initializeAccessibleValueHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:330:29)
at HSlider.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleSlider.js:77:14)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/Slider.js:326:10)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/HSlider.js:27:5)
at new ControllerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/js/common/view/ControllerNode.js:77:20)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:54:37 AM

----------------------------------

gene-expression-essentials : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/gene-expression-essentials_en.html?continuousTest=%7B%22test%22%3A%5B%22gene-expression-essentials%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629276877034%22%2C%22timestamp%22%3A1629279291270%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: scientific notation is not supported: 1.9e-8
Error: Assertion failed: scientific notation is not supported: 1.9e-8
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/dot/js/Utils.js:835:17)
at HSlider.updateSiblingStepAttribute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:920:46)
at enabledRangeObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:328:16)
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/axon/js/Property.js:378:5)
at HSlider.initializeAccessibleValueHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:330:29)
at HSlider.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleSlider.js:77:14)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/Slider.js:326:10)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/HSlider.js:27:5)
at new ControllerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/js/common/view/ControllerNode.js:77:20)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:54:37 AM

----------------------------------

gene-expression-essentials : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/gene-expression-essentials_en.html?continuousTest=%7B%22test%22%3A%5B%22gene-expression-essentials%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1629276877034%22%2C%22timestamp%22%3A1629288034282%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: scientific notation is not supported: 1.9e-8
Error: Assertion failed: scientific notation is not supported: 1.9e-8
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/dot/js/Utils.js:835:17)
at HSlider.updateSiblingStepAttribute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:920:46)
at enabledRangeObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:328:16)
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/axon/js/Property.js:378:5)
at HSlider.initializeAccessibleValueHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:330:29)
at HSlider.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleSlider.js:77:14)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/Slider.js:326:10)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/HSlider.js:27:5)
at new ControllerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/js/common/view/ControllerNode.js:77:20)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:54:37 AM

----------------------------------

gene-expression-essentials : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/gene-expression-essentials_en.html?continuousTest=%7B%22test%22%3A%5B%22gene-expression-essentials%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1629276877034%22%2C%22timestamp%22%3A1629298472456%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: scientific notation is not supported: 1.9e-8
Error: Assertion failed: scientific notation is not supported: 1.9e-8
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/dot/js/Utils.js:835:17)
at HSlider.updateSiblingStepAttribute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:920:46)
at enabledRangeObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:328:16)
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/axon/js/Property.js:378:5)
at HSlider.initializeAccessibleValueHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleValueHandler.js:330:29)
at HSlider.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/accessibility/AccessibleSlider.js:77:14)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/Slider.js:326:10)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/sun/js/HSlider.js:27:5)
at new ControllerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629276877034/gene-expression-essentials/js/common/view/ControllerNode.js:77:20)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:54:37 AM
```

**Comment by jbphet** [comment]
The root cause of this was fixed in https://github.com/phetsims/dot/commit/e585d101f7b238f25072baa3f2d38e55cc63293c, a discussion of the problem can be found starting at https://github.com/phetsims/dot/issues/109#issuecomment-900570141.  Closing.
