### ISSUE TITLE
CT all returned solveCubicRootsReal roots should be finite

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gene-expression-essentials#140]
```
gene-expression-essentials : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/gene-expression-essentials/gene-expression-essentials_en.html?continuousTest=%7B%22test%22%3A%5B%22gene-expression-essentials%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1630381649945%22%2C%22timestamp%22%3A1630400917641%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: All returned solveCubicRootsReal roots should be finite
Error: Assertion failed: All returned solveCubicRootsReal roots should be finite
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/dot/js/Utils.js:489:47
at Array.forEach (<anonymous>)
at solveCubicRootsReal (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/dot/js/Utils.js:489:30)
at Cubic.intersection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/kite/js/segments/Cubic.js:807:16)
at Cubic.windingIntersection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/kite/js/segments/Cubic.js:836:23)
at Shape.windingIntersection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/kite/js/Shape.js:1375:41)
at Shape.containsPoint (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/kite/js/Shape.js:1280:17)
at Path.containsPointSelf (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/scenery/js/nodes/Path.js:497:32)
at Picker.recursiveHitTest (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/scenery/js/util/Picker.js:205:22)
id: Bayes Chrome
Snapshot from 8/30/2021, 9:47:29 PM
```

**Comment by jbphet** [comment]
I was unable to duplicate this locally using an unbuilt version and the query parameters listed above, i.e. `brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true`.  The assertion is being thrown in `dot/Utils.js`, and I can see three commits in the history for this file from yesterday, and at least one of them looks like it could easily be related.  My guess is that it was a short-term problem.

I'll check CT tomorrow and, if this problem is no longer occurring, I'll assume it has been fixed.

**Comment by jbphet** [comment]
Well, it seems to still be occurring, though rarely.  It happened on CT this morn at 8:38 AM, here's a screenshot:

![image](https://user-images.githubusercontent.com/3082831/131705729-962c9196-51a0-49c3-be30-2f5d0589b48b.png)

I still can't duplicate it locally so far, even after running fuzz testing for 30 minutes.  @jonathanolson - Since it seems like this may well be related to recent commits in `dot/Utils.js`, can you offer any insights?

**Comment by jonathanolson** [comment]
Hopefully this will go away with https://github.com/phetsims/dot/commit/414c2f56680f0d3f50443090a59ad72879f0a752, let me know if it doesn't.
